/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jc.sudoku;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import java.util.Random;

import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.SudokuCellValueFilter;

import com.jc.sudoku.components.Cell;
import com.jc.sudoku.components.CellValueType;
import com.jc.sudoku.components.SudokuGrid;
import com.jc.sudoku.exception.SudokuException;

/**
 *
 * @author d3m0n
 */
public class SudokuGUI extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 3010441491278721862L;

	/**
     * Creates new form SudokuGUI
     */
    public SudokuGUI() {
        initComponents();
        createComponentMap();
        setLocationRelativeTo(null);
        //hintButton.setVisible(false);
        SudokuGrid solvedGrid = new SudokuCreator(SudokuCreator.EASY_LEVEL).createSudoku();
        this.currentSolvedGame = solvedGrid;
        populateInputFrame(solvedGrid);
        hintButton.setVisible(true);
    }
    
    private Map<String, Component> componentMap;
    
    private SudokuGrid currentSolvedGame = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c00 = new javax.swing.JTextField();
        c22 = new javax.swing.JTextField();
        c05 = new javax.swing.JTextField();
        c01 = new javax.swing.JTextField();
        c02 = new javax.swing.JTextField();
        c10 = new javax.swing.JTextField();
        c11 = new javax.swing.JTextField();
        c12 = new javax.swing.JTextField();
        c20 = new javax.swing.JTextField();
        c21 = new javax.swing.JTextField();
        c30 = new javax.swing.JTextField();
        c31 = new javax.swing.JTextField();
        c32 = new javax.swing.JTextField();
        c40 = new javax.swing.JTextField();
        c42 = new javax.swing.JTextField();
        c41 = new javax.swing.JTextField();
        c52 = new javax.swing.JTextField();
        c51 = new javax.swing.JTextField();
        c50 = new javax.swing.JTextField();
        c62 = new javax.swing.JTextField();
        c61 = new javax.swing.JTextField();
        c60 = new javax.swing.JTextField();
        c70 = new javax.swing.JTextField();
        c71 = new javax.swing.JTextField();
        c72 = new javax.swing.JTextField();
        c03 = new javax.swing.JTextField();
        c04 = new javax.swing.JTextField();
        c13 = new javax.swing.JTextField();
        c14 = new javax.swing.JTextField();
        c15 = new javax.swing.JTextField();
        c25 = new javax.swing.JTextField();
        c23 = new javax.swing.JTextField();
        c24 = new javax.swing.JTextField();
        c33 = new javax.swing.JTextField();
        c34 = new javax.swing.JTextField();
        c35 = new javax.swing.JTextField();
        c43 = new javax.swing.JTextField();
        c44 = new javax.swing.JTextField();
        c45 = new javax.swing.JTextField();
        c53 = new javax.swing.JTextField();
        c54 = new javax.swing.JTextField();
        c55 = new javax.swing.JTextField();
        c63 = new javax.swing.JTextField();
        c64 = new javax.swing.JTextField();
        c65 = new javax.swing.JTextField();
        c73 = new javax.swing.JTextField();
        c74 = new javax.swing.JTextField();
        c75 = new javax.swing.JTextField();
        c06 = new javax.swing.JTextField();
        c16 = new javax.swing.JTextField();
        c26 = new javax.swing.JTextField();
        c36 = new javax.swing.JTextField();
        c46 = new javax.swing.JTextField();
        c56 = new javax.swing.JTextField();
        c66 = new javax.swing.JTextField();
        c76 = new javax.swing.JTextField();
        c07 = new javax.swing.JTextField();
        c17 = new javax.swing.JTextField();
        c27 = new javax.swing.JTextField();
        c37 = new javax.swing.JTextField();
        c47 = new javax.swing.JTextField();
        c57 = new javax.swing.JTextField();
        c67 = new javax.swing.JTextField();
        c77 = new javax.swing.JTextField();
        c18 = new javax.swing.JTextField();
        c48 = new javax.swing.JTextField();
        c58 = new javax.swing.JTextField();
        c08 = new javax.swing.JTextField();
        c28 = new javax.swing.JTextField();
        c38 = new javax.swing.JTextField();
        c68 = new javax.swing.JTextField();
        c78 = new javax.swing.JTextField();
        c80 = new javax.swing.JTextField();
        c81 = new javax.swing.JTextField();
        c82 = new javax.swing.JTextField();
        c83 = new javax.swing.JTextField();
        c84 = new javax.swing.JTextField();
        c85 = new javax.swing.JTextField();
        c86 = new javax.swing.JTextField();
        c87 = new javax.swing.JTextField();
        c88 = new javax.swing.JTextField();
        jSeparator00 = new javax.swing.JSeparator();
        jSeparator01 = new javax.swing.JSeparator();
        jSeparator02 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        clearButton = new javax.swing.JButton();
        solveButton = new javax.swing.JButton();
        hintButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newGameMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku");
        setPreferredSize(new java.awt.Dimension(360, 465));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c00.setName("c00"); // NOI18N
        c00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c00ActionPerformed(evt);
            }
        });
        getContentPane().add(c00, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        c22.setName("c22"); // NOI18N
        c22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c22ActionPerformed(evt);
            }
        });
        getContentPane().add(c22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 40, 40));

        c05.setName("c05"); // NOI18N
        c05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c05ActionPerformed(evt);
            }
        });
        getContentPane().add(c05, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 40, 40));

        c01.setName("c01"); // NOI18N
        c01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c01ActionPerformed(evt);
            }
        });
        getContentPane().add(c01, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        c02.setName("c02"); // NOI18N
        c02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c02ActionPerformed(evt);
            }
        });
        getContentPane().add(c02, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 40, 40));

        c10.setName("c10"); // NOI18N
        c10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c10ActionPerformed(evt);
            }
        });
        getContentPane().add(c10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 40, 40));

        c11.setName("c11"); // NOI18N
        c11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c11ActionPerformed(evt);
            }
        });
        getContentPane().add(c11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 40));

        c12.setName("c12"); // NOI18N
        c12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c12ActionPerformed(evt);
            }
        });
        getContentPane().add(c12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 40, 40));

        c20.setName("c20"); // NOI18N
        c20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c20ActionPerformed(evt);
            }
        });
        getContentPane().add(c20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 40, 40));

        c21.setName("c21"); // NOI18N
        c21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c21ActionPerformed(evt);
            }
        });
        getContentPane().add(c21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 40, 40));

        c30.setName("c30"); // NOI18N
        c30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c30ActionPerformed(evt);
            }
        });
        getContentPane().add(c30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 40, 40));

        c31.setName("c31"); // NOI18N
        c31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c31ActionPerformed(evt);
            }
        });
        getContentPane().add(c31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 40, 40));

        c32.setName("c32"); // NOI18N
        c32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c32ActionPerformed(evt);
            }
        });
        getContentPane().add(c32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 40, 40));

        c40.setName("c40"); // NOI18N
        c40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c40ActionPerformed(evt);
            }
        });
        getContentPane().add(c40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 40, 40));

        c42.setName("c42"); // NOI18N
        c42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c42ActionPerformed(evt);
            }
        });
        getContentPane().add(c42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 40, 40));

        c41.setName("c41"); // NOI18N
        c41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c41ActionPerformed(evt);
            }
        });
        getContentPane().add(c41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 40, 40));

        c52.setName("c52"); // NOI18N
        c52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c52ActionPerformed(evt);
            }
        });
        getContentPane().add(c52, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 40, 40));

        c51.setName("c51"); // NOI18N
        c51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c51ActionPerformed(evt);
            }
        });
        getContentPane().add(c51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 40, 40));

        c50.setName("c50"); // NOI18N
        c50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c50ActionPerformed(evt);
            }
        });
        getContentPane().add(c50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 40, 40));

        c62.setName("c62"); // NOI18N
        c62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c62ActionPerformed(evt);
            }
        });
        getContentPane().add(c62, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 40, 40));

        c61.setName("c61"); // NOI18N
        c61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c61ActionPerformed(evt);
            }
        });
        getContentPane().add(c61, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 40, 40));

        c60.setName("c60"); // NOI18N
        c60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c60ActionPerformed(evt);
            }
        });
        getContentPane().add(c60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 40, 40));

        c70.setName("c70"); // NOI18N
        c70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c70ActionPerformed(evt);
            }
        });
        getContentPane().add(c70, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 40, 40));

        c71.setName("c71"); // NOI18N
        c71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c71ActionPerformed(evt);
            }
        });
        getContentPane().add(c71, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 40, 40));

        c72.setName("c72"); // NOI18N
        c72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c72ActionPerformed(evt);
            }
        });
        getContentPane().add(c72, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 40, 40));

        c03.setName("c03"); // NOI18N
        c03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c03ActionPerformed(evt);
            }
        });
        getContentPane().add(c03, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 40, 40));

        c04.setName("c04"); // NOI18N
        c04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c04ActionPerformed(evt);
            }
        });
        getContentPane().add(c04, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 40, 40));

        c13.setName("c13"); // NOI18N
        c13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c13ActionPerformed(evt);
            }
        });
        getContentPane().add(c13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 40, 40));

        c14.setName("c14"); // NOI18N
        c14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c14ActionPerformed(evt);
            }
        });
        getContentPane().add(c14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 40, 40));

        c15.setName("c15"); // NOI18N
        c15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c15ActionPerformed(evt);
            }
        });
        getContentPane().add(c15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 40, 40));

        c25.setName("c25"); // NOI18N
        c25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c25ActionPerformed(evt);
            }
        });
        getContentPane().add(c25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 40, 40));

        c23.setName("c23"); // NOI18N
        c23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c23ActionPerformed(evt);
            }
        });
        getContentPane().add(c23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 40, 40));

        c24.setName("c24"); // NOI18N
        c24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c24ActionPerformed(evt);
            }
        });
        getContentPane().add(c24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 40, 40));

        c33.setName("c33"); // NOI18N
        c33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c33ActionPerformed(evt);
            }
        });
        getContentPane().add(c33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 40, 40));

        c34.setName("c34"); // NOI18N
        c34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c34ActionPerformed(evt);
            }
        });
        getContentPane().add(c34, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 40, 40));

        c35.setName("c35"); // NOI18N
        c35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c35ActionPerformed(evt);
            }
        });
        getContentPane().add(c35, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 40, 40));

        c43.setName("c43"); // NOI18N
        c43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c43ActionPerformed(evt);
            }
        });
        getContentPane().add(c43, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 40, 40));

        c44.setName("c44"); // NOI18N
        c44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c44ActionPerformed(evt);
            }
        });
        getContentPane().add(c44, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 40, 40));

        c45.setName("c45"); // NOI18N
        c45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c45ActionPerformed(evt);
            }
        });
        getContentPane().add(c45, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 40, 40));

        c53.setName("c53"); // NOI18N
        c53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c53ActionPerformed(evt);
            }
        });
        getContentPane().add(c53, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 40, 40));

        c54.setName("c54"); // NOI18N
        c54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c54ActionPerformed(evt);
            }
        });
        getContentPane().add(c54, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 40, 40));

        c55.setName("c55"); // NOI18N
        c55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c55ActionPerformed(evt);
            }
        });
        getContentPane().add(c55, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 40, 40));

        c63.setName("c63"); // NOI18N
        c63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c63ActionPerformed(evt);
            }
        });
        getContentPane().add(c63, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 40, 40));

        c64.setName("c64"); // NOI18N
        c64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c64ActionPerformed(evt);
            }
        });
        getContentPane().add(c64, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 40, 40));

        c65.setName("c65"); // NOI18N
        c65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c65ActionPerformed(evt);
            }
        });
        getContentPane().add(c65, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 40, 40));

        c73.setName("c73"); // NOI18N
        c73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c73ActionPerformed(evt);
            }
        });
        getContentPane().add(c73, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 40, 40));

        c74.setName("c74"); // NOI18N
        c74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c74ActionPerformed(evt);
            }
        });
        getContentPane().add(c74, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 40, 40));

        c75.setName("c75"); // NOI18N
        c75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c75ActionPerformed(evt);
            }
        });
        getContentPane().add(c75, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 40, 40));

        c06.setName("c06"); // NOI18N
        c06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c06ActionPerformed(evt);
            }
        });
        getContentPane().add(c06, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 40, 40));

        c16.setName("c16"); // NOI18N
        c16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c16ActionPerformed(evt);
            }
        });
        getContentPane().add(c16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 40, 40));

        c26.setName("c26"); // NOI18N
        c26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c26ActionPerformed(evt);
            }
        });
        getContentPane().add(c26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 40, 40));

        c36.setName("c36"); // NOI18N
        c36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c36ActionPerformed(evt);
            }
        });
        getContentPane().add(c36, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 40, 40));

        c46.setName("c46"); // NOI18N
        c46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c46ActionPerformed(evt);
            }
        });
        getContentPane().add(c46, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 40, 40));

        c56.setName("c56"); // NOI18N
        c56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c56ActionPerformed(evt);
            }
        });
        getContentPane().add(c56, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 40, 40));

        c66.setName("c66"); // NOI18N
        c66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c66ActionPerformed(evt);
            }
        });
        getContentPane().add(c66, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 40, 40));

        c76.setName("c76"); // NOI18N
        c76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c76ActionPerformed(evt);
            }
        });
        getContentPane().add(c76, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 40, 40));

        c07.setName("c07"); // NOI18N
        c07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c07ActionPerformed(evt);
            }
        });
        getContentPane().add(c07, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 40, 40));

        c17.setName("c17"); // NOI18N
        c17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c17ActionPerformed(evt);
            }
        });
        getContentPane().add(c17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 40, 40));

        c27.setName("c27"); // NOI18N
        c27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c27ActionPerformed(evt);
            }
        });
        getContentPane().add(c27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 40, 40));

        c37.setName("c37"); // NOI18N
        c37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c37ActionPerformed(evt);
            }
        });
        getContentPane().add(c37, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 40, 40));

        c47.setName("c47"); // NOI18N
        c47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c47ActionPerformed(evt);
            }
        });
        getContentPane().add(c47, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 40, 40));

        c57.setName("c57"); // NOI18N
        c57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c57ActionPerformed(evt);
            }
        });
        getContentPane().add(c57, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 40, 40));

        c67.setName("c67"); // NOI18N
        c67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c67ActionPerformed(evt);
            }
        });
        getContentPane().add(c67, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 40, 40));

        c77.setName("c77"); // NOI18N
        c77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c77ActionPerformed(evt);
            }
        });
        getContentPane().add(c77, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 40, 40));

        c18.setName("c18"); // NOI18N
        c18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c18ActionPerformed(evt);
            }
        });
        getContentPane().add(c18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 40, 40));

        c48.setName("c48"); // NOI18N
        c48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c48ActionPerformed(evt);
            }
        });
        getContentPane().add(c48, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 40, 40));

        c58.setName("c58"); // NOI18N
        c58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c58ActionPerformed(evt);
            }
        });
        getContentPane().add(c58, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 40, 40));

        c08.setName("c08"); // NOI18N
        c08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c08ActionPerformed(evt);
            }
        });
        getContentPane().add(c08, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 40, 40));

        c28.setName("c28"); // NOI18N
        c28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c28ActionPerformed(evt);
            }
        });
        getContentPane().add(c28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 40, 40));

        c38.setName("c38"); // NOI18N
        c38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c38ActionPerformed(evt);
            }
        });
        getContentPane().add(c38, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 40, 40));

        c68.setName("c68"); // NOI18N
        c68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c68ActionPerformed(evt);
            }
        });
        getContentPane().add(c68, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 40, 40));

        c78.setName("c78"); // NOI18N
        c78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c78ActionPerformed(evt);
            }
        });
        getContentPane().add(c78, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 40, 40));

        c80.setName("c80"); // NOI18N
        c80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c80ActionPerformed(evt);
            }
        });
        getContentPane().add(c80, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 40, 40));

        c81.setName("c81"); // NOI18N
        c81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c81ActionPerformed(evt);
            }
        });
        getContentPane().add(c81, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 40, 40));

        c82.setName("c82"); // NOI18N
        c82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c82ActionPerformed(evt);
            }
        });
        getContentPane().add(c82, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 40, 40));

        c83.setName("c83"); // NOI18N
        c83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c83ActionPerformed(evt);
            }
        });
        getContentPane().add(c83, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 40, 40));

        c84.setName("c84"); // NOI18N
        c84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c84ActionPerformed(evt);
            }
        });
        getContentPane().add(c84, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 40, 40));

        c85.setName("c85"); // NOI18N
        c85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c85ActionPerformed(evt);
            }
        });
        getContentPane().add(c85, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 40, 40));

        c86.setName("c86"); // NOI18N
        c86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c86ActionPerformed(evt);
            }
        });
        getContentPane().add(c86, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 40, 40));

        c87.setName("c87"); // NOI18N
        c87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c87ActionPerformed(evt);
            }
        });
        getContentPane().add(c87, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 40, 40));

        c88.setName("c88"); // NOI18N
        c88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c88ActionPerformed(evt);
            }
        });
        getContentPane().add(c88, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 40, 40));

        jSeparator00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator00, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 120));

        jSeparator01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator01, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 120, 120));

        jSeparator02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator02, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 120, 120));

        jSeparator10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 120));

        jSeparator11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 120, 120));

        jSeparator12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 120, 120));

        jSeparator20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 120, 120));

        jSeparator21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 120, 120));

        jSeparator22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 120, 120));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 110, -1));

        solveButton.setText("Solve");
        solveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(solveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 100, -1));

        hintButton.setText("Hint");
        hintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hintButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 80, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 360, 30));

        jMenu1.setText("Menu");

        newGameMenuItem.setText("New Game");
        newGameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(newGameMenuItem);

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(aboutMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c22ActionPerformed

    private void c05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c05ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c05ActionPerformed

    private void c01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c01ActionPerformed

    private void c02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c02ActionPerformed

    private void c10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c10ActionPerformed

    private void c11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c11ActionPerformed

    private void c12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c12ActionPerformed

    private void c20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c20ActionPerformed

    private void c21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c21ActionPerformed

    private void c30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c30ActionPerformed

    private void c31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c31ActionPerformed

    private void c32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c32ActionPerformed

    private void c40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c40ActionPerformed

    private void c42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c42ActionPerformed

    private void c41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c41ActionPerformed

    private void c52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c52ActionPerformed

    private void c51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c51ActionPerformed

    private void c50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c50ActionPerformed

    private void c62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c62ActionPerformed

    private void c61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c61ActionPerformed

    private void c60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c60ActionPerformed

    private void c70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c70ActionPerformed

    private void c71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c71ActionPerformed

    private void c72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c72ActionPerformed

    private void c80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c80ActionPerformed

    private void c81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c81ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c81ActionPerformed

    private void c82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c82ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c82ActionPerformed

    private void c00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c00ActionPerformed

    private void c03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c03ActionPerformed

    private void c04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c04ActionPerformed

    private void c13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c13ActionPerformed

    private void c14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c14ActionPerformed

    private void c15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c15ActionPerformed

    private void c25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c25ActionPerformed

    private void c23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c23ActionPerformed

    private void c24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c24ActionPerformed

    private void c33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c33ActionPerformed

    private void c34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c34ActionPerformed

    private void c35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c35ActionPerformed

    private void c43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c43ActionPerformed

    private void c44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c44ActionPerformed

    private void c45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c45ActionPerformed

    private void c53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c53ActionPerformed

    private void c54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c54ActionPerformed

    private void c55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c55ActionPerformed

    private void c63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c63ActionPerformed

    private void c64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c64ActionPerformed

    private void c65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c65ActionPerformed

    private void c73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c73ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c73ActionPerformed

    private void c74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c74ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c74ActionPerformed

    private void c75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c75ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c75ActionPerformed

    private void c85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c85ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c85ActionPerformed

    private void c84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c84ActionPerformed

    private void c83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c83ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c83ActionPerformed

    private void c06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c06ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c06ActionPerformed

    private void c16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c16ActionPerformed

    private void c26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c26ActionPerformed

    private void c36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c36ActionPerformed

    private void c46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c46ActionPerformed

    private void c56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c56ActionPerformed

    private void c66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c66ActionPerformed

    private void c76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c76ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c76ActionPerformed

    private void c86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c86ActionPerformed

    private void c07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c07ActionPerformed

    private void c17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c17ActionPerformed

    private void c27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c27ActionPerformed

    private void c37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c37ActionPerformed

    private void c47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c47ActionPerformed

    private void c57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c57ActionPerformed

    private void c67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c67ActionPerformed

    private void c77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c77ActionPerformed

    private void c87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c87ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c87ActionPerformed

    private void c18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c18ActionPerformed

    private void c48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c48ActionPerformed

    private void c58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c58ActionPerformed

    private void c08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c08ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c08ActionPerformed

    private void c28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c28ActionPerformed

    private void c38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c38ActionPerformed

    private void c88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c88ActionPerformed

    private void c68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c68ActionPerformed

    private void c78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c78ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c78ActionPerformed

    private void solveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButtonActionPerformed
    		hintButton.setVisible(false);
    		if(this.currentSolvedGame!=null) {
    			boolean isValid = validateUserInput();
    			if(!isValid) {
    				return;
    			}
    		}else {
    			boolean isSuccessful = solveGridBasedOnUserInputs();
    			if(!isSuccessful) {
    				return;
    			}
    			
    		}
    		populateFrame(this.currentSolvedGame);
    		jLabel1.setText("Solved!");
    }//GEN-LAST:event_solveButtonActionPerformed

	private boolean solveGridBasedOnUserInputs() {
		SudokuGrid grid = new SudokuGrid();
		int inputCellCount = 0;
		for (int i = 0; i < 9; i++) {
			for (int j = 0; j < 9; j++) {
				javax.swing.JTextField cell = (javax.swing.JTextField) getComponentByName("c" + i + "" + j);
				if (cell.getText() != null && !cell.getText().trim().equals("")) {
					int value = Integer.valueOf(cell.getText());
					try {
						grid.setValue(i, j, value, CellValueType.USER);
					} catch (SudokuException se) {
						jLabel1.setText(se.getUserMsg());
						((javax.swing.JTextField) getComponentByName("c" + se.getX() + "" + se.getY()))
								.setBackground(Color.RED);
					}
					inputCellCount++;
				}
			}
		}
		if (inputCellCount < 17) {
			jLabel1.setText("More values needed to solve this Sudoku!");
			return false;
		}
		if (grid.isSolved) {
			this.currentSolvedGame = grid;
			return true;
		}
		SudokuSolver solver = new SudokuSolver(true);
		try {
			SudokuGrid solvedGrid = solver.solveSudoku(grid);
			this.currentSolvedGame = solvedGrid;
		} catch (SudokuException se) {
			jLabel1.setText("Cannot solve. Insufficient or incorrect values entered!");
			hintButton.setVisible(false);
			return false;
		}
		return true;
	}

	private boolean validateUserInput() {
    		boolean validationFlag = true;
    		for(int i=0; i<9; i++){
            for (int j=0; j<9; j++){
                javax.swing.JTextField cell = (javax.swing.JTextField)getComponentByName("c"+i+""+j);
                if(cell.getText()!=null && !cell.getText().trim().equals("")){ //If we have value present in UI
                		//And that value is a Solved value i.e. not GENERATED or HIT then mark it as USER input
                		if(this.currentSolvedGame.getCell(i, j).getValueType()==CellValueType.SOLVED) {
                			this.currentSolvedGame.getCell(i, j).setValueType(CellValueType.USER);
                		}
                		//Validation for incorrect value
                    int value = Integer.valueOf(cell.getText());
                    if(value != this.currentSolvedGame.getCell(i, j).getValue()) {
                    		jLabel1.setText("Incorrect value, should be "+this.currentSolvedGame.getCell(i, j).getValue());
                    		validationFlag = false;
                    		cell.setBackground(Color.RED);
                    		break;
                    }
                }
            }
        }
		return validationFlag;
	}

	private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "This will clear values from all cells. Are you sure?", 
                "Clear confirmation",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(option == JOptionPane.YES_OPTION){
            clearAll();
            jLabel1.setText("Cleared!");
            hintButton.setVisible(false);
        }
    }//GEN-LAST:event_clearButtonActionPerformed

    private void newGameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameMenuItemActionPerformed
        clearAll();
        SudokuGrid solvedGrid = new SudokuCreator(SudokuCreator.HARD_LEVEL).createSudoku();
        this.currentSolvedGame = solvedGrid;
        populateInputFrame(solvedGrid);
        hintButton.setVisible(true);
    }//GEN-LAST:event_newGameMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "Developed by JoyC (2018)", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void hintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonActionPerformed
    		if(this.currentSolvedGame!=null) {
    			boolean isValid = validateUserInput();
    			if(!isValid) {
    				return;
    			}
		}else {
			boolean isSuccessful = solveGridBasedOnUserInputs();
			if(!isSuccessful) {
				return;
			}
        }
	        
        Cell cell = null;
        while(cell == null){
            final int x = new Random().nextInt(9);
            final int y = new Random().nextInt(9);
            
            javax.swing.JTextField uiCell = (javax.swing.JTextField)getComponentByName("c"+x+""+y);
            //We cannot provide hint for a cell with value
            if(uiCell.getText()==null || uiCell.getText().trim().equals("")){
            //We cannot provide hint for a cell which was GENERATED or USER (taken care in validation) or HINT 
	            if(this.currentSolvedGame.getCell(x, y).getValueType()==CellValueType.SOLVED){
	            		cell = this.currentSolvedGame.getCell(x, y);
	            		cell.setValueType(CellValueType.HINT);
	            }
            }
        }
        javax.swing.JTextField hintCell = (javax.swing.JTextField)getComponentByName("c"+cell.getX()+""+cell.getY());
        hintCell.setText(cell.getValue().toString());
        hintCell.setBackground(Color.ORANGE);
        
        hintButton.setEnabled(false);
        jLabel1.setText("Try now. You will need to wait for the next hint.");
        int delay = 28000;
        Timer timer = new Timer(delay, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
               hintButton.setEnabled(true);
               jLabel1.setText("");
            }
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_hintButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuGUI().setVisible(true);
            }
        });
    }
    
    private void createComponentMap() {
        componentMap = new HashMap<>();
        Component[] components = getContentPane().getComponents();
        Font font1 = new Font(Font.MONOSPACED, Font.PLAIN, 20);
        for(Component component : components){
            if(component.getName()!=null){
                componentMap.put(component.getName(), component);
                if(component instanceof javax.swing.JTextField){
                    javax.swing.JTextField cell = (javax.swing.JTextField) component;
                    javax.swing.text.PlainDocument doc = (javax.swing.text.PlainDocument)cell.getDocument();
                    doc.setDocumentFilter(new SudokuCellValueFilter());
                    doc.addDocumentListener(new DocumentListener() {
						
						@Override
						public void removeUpdate(DocumentEvent e) {
							jLabel1.setText("");
						}
						
						@Override
						public void insertUpdate(DocumentEvent e) {
							if(currentSolvedGame!=null) {
								boolean incorrectValueFound = false;
								for(int i=0; i<9; i++){
						            for (int j=0; j<9; j++){
						                javax.swing.JTextField cell = (javax.swing.JTextField)getComponentByName("c"+i+""+j);
						                if (cell.getText() == null || cell.getText().trim().equals("")) {
						                		jLabel1.setText("");
						                		return;
						                }else if(!cell.getText().equals(String.valueOf(currentSolvedGame.getCell(i, j).getValue()))) {
						                		incorrectValueFound = true;
						                }
						            }
								}
								if(incorrectValueFound) {
									jLabel1.setText("Incorrect value found!");
								}else {
									jLabel1.setText("Nice work! You have solved the Sudoku");
								}
							}
						}
						
						@Override
						public void changedUpdate(DocumentEvent e) {
							// TODO Auto-generated method stub
							
						}
					});
                    
                    cell.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                    cell.setFont(font1);
                }
            }
        }
    }

    public Component getComponentByName(String name) {
            if (componentMap.containsKey(name)) {
                    return (Component) componentMap.get(name);
            }
            else return null;
    }
    
    private void populateFrame(SudokuGrid grid){
        for(int i=0; i<9; i++){
            for (int j=0; j<9; j++){
                javax.swing.JTextField cell = (javax.swing.JTextField)getComponentByName("c"+i+""+j);
                Integer value = grid.getCell(i, j).getValue();
                if(value!=null){
                    cell.setText(grid.getCell(i, j).getValue().toString());
                }
                if(grid.getCell(i, j).getValueType()==CellValueType.GENERATED){
                    cell.setBackground(Color.cyan);
                }else if(grid.getCell(i, j).getValueType()==CellValueType.HINT) {
                		cell.setBackground(Color.ORANGE);
                }else if(grid.getCell(i, j).getValueType()==CellValueType.USER) {
                		cell.setBackground(Color.YELLOW);
                }
            }
        }
    }
    
    private void populateInputFrame(SudokuGrid grid){
        for(int i=0; i<9; i++){
            for (int j=0; j<9; j++){
                javax.swing.JTextField cell = (javax.swing.JTextField)getComponentByName("c"+i+""+j);
                Integer value = grid.getCell(i, j).getValue();
                if(grid.getCell(i, j).getValueType()==CellValueType.GENERATED && value!=null) {
                		cell.setText(grid.getCell(i, j).getValue().toString());
                }
                if(CellValueType.GENERATED==grid.getCell(i, j).getValueType()){ 
                    cell.setBackground(Color.cyan);
                    cell.setEditable(false);
                } 
                jLabel1.setText("");
            }
        }
    }
    
    private void clearAll(){
    		this.currentSolvedGame = null;
        for(int i=0; i<9; i++){
            for (int j=0; j<9; j++){
                javax.swing.JTextField cell = (javax.swing.JTextField)getComponentByName("c"+i+""+j);
                cell.setText("");
                cell.setBackground(Color.white);
                cell.setEditable(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTextField c00;
    private javax.swing.JTextField c01;
    private javax.swing.JTextField c02;
    private javax.swing.JTextField c03;
    private javax.swing.JTextField c04;
    private javax.swing.JTextField c05;
    private javax.swing.JTextField c06;
    private javax.swing.JTextField c07;
    private javax.swing.JTextField c08;
    private javax.swing.JTextField c10;
    private javax.swing.JTextField c11;
    private javax.swing.JTextField c12;
    private javax.swing.JTextField c13;
    private javax.swing.JTextField c14;
    private javax.swing.JTextField c15;
    private javax.swing.JTextField c16;
    private javax.swing.JTextField c17;
    private javax.swing.JTextField c18;
    private javax.swing.JTextField c20;
    private javax.swing.JTextField c21;
    private javax.swing.JTextField c22;
    private javax.swing.JTextField c23;
    private javax.swing.JTextField c24;
    private javax.swing.JTextField c25;
    private javax.swing.JTextField c26;
    private javax.swing.JTextField c27;
    private javax.swing.JTextField c28;
    private javax.swing.JTextField c30;
    private javax.swing.JTextField c31;
    private javax.swing.JTextField c32;
    private javax.swing.JTextField c33;
    private javax.swing.JTextField c34;
    private javax.swing.JTextField c35;
    private javax.swing.JTextField c36;
    private javax.swing.JTextField c37;
    private javax.swing.JTextField c38;
    private javax.swing.JTextField c40;
    private javax.swing.JTextField c41;
    private javax.swing.JTextField c42;
    private javax.swing.JTextField c43;
    private javax.swing.JTextField c44;
    private javax.swing.JTextField c45;
    private javax.swing.JTextField c46;
    private javax.swing.JTextField c47;
    private javax.swing.JTextField c48;
    private javax.swing.JTextField c50;
    private javax.swing.JTextField c51;
    private javax.swing.JTextField c52;
    private javax.swing.JTextField c53;
    private javax.swing.JTextField c54;
    private javax.swing.JTextField c55;
    private javax.swing.JTextField c56;
    private javax.swing.JTextField c57;
    private javax.swing.JTextField c58;
    private javax.swing.JTextField c60;
    private javax.swing.JTextField c61;
    private javax.swing.JTextField c62;
    private javax.swing.JTextField c63;
    private javax.swing.JTextField c64;
    private javax.swing.JTextField c65;
    private javax.swing.JTextField c66;
    private javax.swing.JTextField c67;
    private javax.swing.JTextField c68;
    private javax.swing.JTextField c70;
    private javax.swing.JTextField c71;
    private javax.swing.JTextField c72;
    private javax.swing.JTextField c73;
    private javax.swing.JTextField c74;
    private javax.swing.JTextField c75;
    private javax.swing.JTextField c76;
    private javax.swing.JTextField c77;
    private javax.swing.JTextField c78;
    private javax.swing.JTextField c80;
    private javax.swing.JTextField c81;
    private javax.swing.JTextField c82;
    private javax.swing.JTextField c83;
    private javax.swing.JTextField c84;
    private javax.swing.JTextField c85;
    private javax.swing.JTextField c86;
    private javax.swing.JTextField c87;
    private javax.swing.JTextField c88;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator00;
    private javax.swing.JSeparator jSeparator01;
    private javax.swing.JSeparator jSeparator02;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JMenuItem newGameMenuItem;
    private javax.swing.JButton solveButton;
    // End of variables declaration//GEN-END:variables
}
